import type { Metadata } from "next";
import { Alegreya, Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { cookies } from "next/headers";

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-alegreya",
});
const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedUsernameCookie = (await cookies()).get("SocialUsername");

  return (
    <>
      <html lang="en" className={`${mulish.variable} ${alegreya.variable}`}>
        <Navbar loggedUsername={loggedUsernameCookie?.value} />
        <body>{children}</body>
      </html>
    </>
  );
}
