import type { Metadata } from "next";
import { Alegreya, Mulish } from "next/font/google";
import "./globals.css";

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-alegreya",
});
const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mulish.variable} ${alegreya.variable}`}>
      <body>
        {/* <h1 className="font-bold italic">ESTE ES UN TITULO</h1>
        <h2 className="font-semibold">Este es un Subtitulo</h2> */}

        {children}
      </body>
    </html>
  );
}
